name: test-suite-e2e-tests-with-build

on:
  workflow_dispatch:
    inputs:
      core_version:
        description: "KMS Core Version"
        default: ""
        type: string
      relayer_version:
        description: "Relayer Image Version"
        default: ""
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  check-changes:
    name: test-suite-e2e-tests-with-build/check-changes
    permissions:
      actions: 'read'
      contents: 'read'
      pull-requests: 'read'
    runs-on: ubuntu-latest
    outputs:
      changes-fhevm: ${{ steps.filter.outputs.fhevm }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            fhevm:
              - 'test-suite/fhevm/**'

  tests:
    name: test-suite-e2e-tests-with-build/tests
    needs: check-changes
    if: ${{ needs.check-changes.outputs.changes-fhevm == 'true' || github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'read'
    runs-on: large_ubuntu_32
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Display Docker and Buildx version
        run: |
          echo "Docker version: $(docker --version)"
          echo "Docker Buildx version: $(docker buildx version)"
          echo "--- Docker Info ---"
          docker info
          echo "-------------------"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_READ_TOKEN }}

      - name: Deploy fhevm Stack
        working-directory: test-suite/fhevm
        env:
          CORE_VERSION: ${{ inputs.core_version }}
          RELAYER_VERSION: ${{ inputs.relayer_version }}
          DOCKER_BUILDKIT: 1
        timeout-minutes: 90
        run: |
          ./fhevm-cli deploy --build

      - name: Run tests
        working-directory: test-suite/fhevm
        run: |
          ./fhevm-cli test input-proof
          ./fhevm-cli test public-decryption
          ./fhevm-cli test user-decryption
          ./fhevm-cli test erc20
          ./fhevm-cli test public-decrypt-http-ebool
          ./fhevm-cli test public-decrypt-http-mixed

      - name: Show logs on test failure
        working-directory: test-suite/fhevm
        if: always()
        run: |
          echo "::group::Relayer Logs"
          ./fhevm-cli logs relayer
          echo "::endgroup::"
          echo "::group::SNS Worker Logs"
          ./fhevm-cli logs sns-worker | grep -v "Selected 0 rows to process"
          echo "::endgroup::"
          echo "::group::Transaction Sender Logs (filtered)"
          ./fhevm-cli logs transaction-sender | grep -v "Selected 0 rows to process"
          echo "::endgroup::"

      - name: Cleanup
        working-directory: test-suite/fhevm
        if: always()
        run: |
          ./fhevm-cli clean
